# Generated by Django 5.2.9 on 2026-04-12 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
